[package]
name = "falcon"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
nu-ansi-term = "0.50.1"
ryu = "1.0.18"
serde = { version = "1.0.204", features = ["derive"] }
toml = "0.8.16"

[profile.release]
opt-level = "s"
lto = true
strip = "symbols"
codegen-units = 1
