# Line number (included) where the selection begins
# Optional, defaults to the 1st row
line_start = 3

# Line number (included) where the selection ends
# Optional, defaults to the last row
line_end = 9

# Global configuration of fractional digits for floating point number
# Optional, can be overridden by configurations in [selected]
# Note:
# fraction_digits configures the maximum length of digits after the decimal point,
# which means that the length of fraction parts depends on the number itself.
# e.g.
# `3.14159` with fraction_digits=2 will be formatted to `3.14`.
# `1.00001` with fraction_digits=4 will be formatted to `1.0`, not `1.0000`.
# `1.00008` with fraction_digits=4 will be formatted to `1.0001`.
# `3` (integer) or `foo` (strings that can't be parsed to number) won't be formatted.
fraction_digits = 2

# The following are selected table
# The order of the columns in the output file is the same as the order of configurations here

# ===========   1st selection   ===========
[[selected]]
# Name of the column that you want to select
name = "时间"
# You can override the column name in the output file by this.
# Optional, defaults to the original name.
rename = "Time"
# fraction_digits for current selection
# Optional, defaults to global fraction_digits
fraction_digits = 0


# ===========   2nd selection   ===========
[[selected]]
name = "Status"

# Replacement for current selection, optional
# Both "old" and "new" should be strings
# Note:
# "old" must fully match to a cell's content to make the replacement happen
[[selected.replacement]]
old = "ON"
new = "1"

[[selected.replacement]]
old = "OFF"
new = "0"

# ===========   3rd selection   ===========
[[selected]]
name = "ErrCode"

[[selected.replacement]]
old = "65535"
new = "7"

# ===========   4th selection   ===========
[[selected]]
name = "Temperature"
rename = "T(F)"
fraction_digits = 1
# use `x` as template variable for cell data
# see https://docs.rs/meval/latest/meval/#supported-expressions for supported expressions
transform = "x*1.8+32"

# ===========   5th selection   ===========
[[selected]]
name = "Var2"
fraction_digits = 6
transform = "max(sin(x),cos(x))"
