line_start = 1
line_end = 999


fraction_digits = 2

[[replacement]]
old = "-17.8"
new = "0"


[[selected]]
name = "a"
rename = "A"
fraction_digits = 0

[[selected.replacement]]
old = "on"
new = "1"

[[selected.replacement]]
old = "off"
new = "0"

[[selected]]
name = "c"
fraction_digits = 1